//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizedOnBoardPart
    {
        public long ID { get; set; }
        public Nullable<long> OnBoardPart { get; set; }
        public Nullable<int> DelegatedTo { get; set; }
        public int ResponsibleUser { get; set; }
        public Nullable<System.DateTime> DatePODue { get; set; }
    }
}
