//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailPlanJob
    {
        public string Job { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> Date_Start { get; set; }
        public string Part { get; set; }
        public string Customer { get; set; }
        public Nullable<long> OnBoardPart { get; set; }
        public int ID { get; set; }
    }
}
