//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacklogPartsList
    {
        public int ID { get; set; }
        public string PartNum { get; set; }
        public string PartFamily { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Extension { get; set; }
        public Nullable<System.DateTime> DateContractStart { get; set; }
        public Nullable<System.DateTime> DateContractEnd { get; set; }
        public string LTA { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
