//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWOStage
    {
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public string CODE_SORT { get; set; }
        public string PROGRAM { get; set; }
        public string PRODUCT_LINE_NAME { get; set; }
        public string JOB { get; set; }
        public string SUFFIX { get; set; }
        public string PART { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> QTY_COMPLETED { get; set; }
        public Nullable<decimal> AMT_SALES { get; set; }
        public Nullable<decimal> AMT_PRICE { get; set; }
        public Nullable<decimal> AMT_PRICE_PER_UNIT { get; set; }
        public Nullable<decimal> AMT_COST { get; set; }
        public string DATE_CLOSED { get; set; }
        public string PERIOD { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
    }
}
