//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DashboardEntities : DbContext
    {
        public DashboardEntities()
            : base("name=DashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Update> Updates { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<OTMonthlyByCompany> OTMonthlyByCompanies { get; set; }
        public virtual DbSet<SalesMonthlyByCompany> SalesMonthlyByCompanies { get; set; }
        public virtual DbSet<SalesDailyByCompany> SalesDailyByCompanies { get; set; }
        public virtual DbSet<SalesStage> SalesStages { get; set; }
        public virtual DbSet<ScrapMonthlyByPlant> ScrapMonthlyByPlants { get; set; }
        public virtual DbSet<CWODailyByPlant> CWODailyByPlants { get; set; }
        public virtual DbSet<ScrapDailyByPlant> ScrapDailyByPlants { get; set; }
        public virtual DbSet<ScrapStage> ScrapStages { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Deliverable> Deliverables { get; set; }
        public virtual DbSet<DeliverableReviewer> DeliverableReviewers { get; set; }
        public virtual DbSet<DeliverableReview> DeliverableReviews { get; set; }
        public virtual DbSet<DeliverableDocument> DeliverableDocuments { get; set; }
        public virtual DbSet<DeliverableComment> DeliverableComments { get; set; }
        public virtual DbSet<DeliverableDetail> DeliverableDetails { get; set; }
        public virtual DbSet<ReviewablesByUser> ReviewablesByUsers { get; set; }
        public virtual DbSet<ProjectTask> ProjectTasks { get; set; }
        public virtual DbSet<ProjectAssignee> ProjectAssignees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<DeliverableStatusByUserID> DeliverableStatusByUserIDs { get; set; }
        public virtual DbSet<PastDueDeliverable> PastDueDeliverables { get; set; }
        public virtual DbSet<DeliverablesDueInNextThirtyDay> DeliverablesDueInNextThirtyDays { get; set; }
        public virtual DbSet<BugTag> BugTags { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<UCFCategory> UCFCategories { get; set; }
        public virtual DbSet<UCFChallenge> UCFChallenges { get; set; }
        public virtual DbSet<UCFAudit> UCFAudits { get; set; }
        public virtual DbSet<UCFArea> UCFAreas { get; set; }
        public virtual DbSet<UCFCriteria> UCFCriterias { get; set; }
        public virtual DbSet<UCFAuditDetail> UCFAuditDetails { get; set; }
        public virtual DbSet<UCFPlantRollupByMonthHalf> UCFPlantRollupByMonthHalves { get; set; }
        public virtual DbSet<UCFAreaTrendByMonthHalf> UCFAreaTrendByMonthHalves { get; set; }
        public virtual DbSet<UCFGoal> UCFGoals { get; set; }
        public virtual DbSet<UCFAction> UCFActions { get; set; }
        public virtual DbSet<UCFPreviousScoresByChallenge> UCFPreviousScoresByChallenges { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<IncentiveRollupByPlant> IncentiveRollupByPlants { get; set; }
        public virtual DbSet<Bug> Bugs { get; set; }
        public virtual DbSet<ProjectsTopLevel> ProjectsTopLevels { get; set; }
        public virtual DbSet<BugsTopLevel> BugsTopLevels { get; set; }
        public virtual DbSet<PrevMaint> PrevMaints { get; set; }
        public virtual DbSet<Meetings> Meetings1 { get; set; }
        public virtual DbSet<UCFAuditHIstoryTopLevel> UCFAuditHIstoryTopLevels { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<UCFAveragesByMonth> UCFAveragesByMonths { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<CWOStage> CWOStages { get; set; }
        public virtual DbSet<UCFAuditDetailLevel> UCFAuditDetailLevels { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<FlashReportRollUp> FlashReportRollUps { get; set; }
        public virtual DbSet<OnTimeDeliveryTrend> OnTimeDeliveryTrends { get; set; }
        public virtual DbSet<OnTimeDeliveryTrendInt> OnTimeDeliveryTrendInts { get; set; }
        public virtual DbSet<FlashReportRollUpAll> FlashReportRollUpAlls { get; set; }
    }
}
