//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableDetail
    {
        public int ID { get; set; }
        public int DelID { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Notes { get; set; }
        public Nullable<int> DelegatedTo { get; set; }
        public Nullable<System.DateTime> DateDelegated { get; set; }
        public string DelegatedReason { get; set; }
    }
}
