//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableStatusByUserID
    {
        public long ID { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Incomplete { get; set; }
        public Nullable<int> CompleteOnTime { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PassedDueComplete { get; set; }
        public Nullable<int> PassedDueIncomplete { get; set; }
    }
}
