//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverableView
    {
        public int ID { get; set; }
        public int DelDetID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> TimeViewed { get; set; }
    }
}
