//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashReportRollUpAll
    {
        public long ID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public Nullable<int> DaysInMonth { get; set; }
        public Nullable<decimal> Cwo { get; set; }
        public Nullable<decimal> CWOGoal { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> Scrap { get; set; }
        public Nullable<decimal> ScrapGoal { get; set; }
        public Nullable<decimal> ScrapAsPercent { get; set; }
        public string PlantCode { get; set; }
        public Nullable<decimal> UCFScore { get; set; }
        public Nullable<decimal> UCFGoal { get; set; }
        public int PlantID { get; set; }
        public Nullable<decimal> PDSales { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Margins { get; set; }
        public Nullable<decimal> MarginPct { get; set; }
        public Nullable<decimal> OnTimePercent { get; set; }
    }
}
