//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int ID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public string UserSubmit { get; set; }
        public string Job { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> InspectionTypeID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<bool> CallOpen { get; set; }
        public Nullable<int> InspectorID { get; set; }
    }
}
