//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOperation
    {
        public string JOB { get; set; }
        public string SUFFIX { get; set; }
        public string SEQ { get; set; }
        public string FILLER1 { get; set; }
        public string WO_INSERT { get; set; }
        public string OPERATION { get; set; }
        public string FLAG_SET_UP { get; set; }
        public string LMO { get; set; }
        public string DESCRIPTION { get; set; }
        public string UM { get; set; }
        public string PART { get; set; }
        public string ROUTER { get; set; }
        public string ROUTER_SEQ { get; set; }
        public string FLAG_OPEN { get; set; }
        public Nullable<decimal> UNITS_OPEN { get; set; }
        public Nullable<decimal> UNITS_COMPLETE { get; set; }
        public Nullable<decimal> PERCENT_COMPLETE { get; set; }
        public Nullable<decimal> UNITS_SCRAP { get; set; }
        public Nullable<decimal> UNITS_COMMITTED { get; set; }
        public Nullable<decimal> DOLLARS_COMMITTED { get; set; }
        public string FLAG_CLOSED { get; set; }
        public string FLAG_SPECIAL_IND { get; set; }
        public Nullable<decimal> SETUP { get; set; }
        public Nullable<decimal> UNITS { get; set; }
        public Nullable<decimal> BURDEN { get; set; }
        public Nullable<decimal> RATE_BURDEN { get; set; }
        public Nullable<decimal> HOURS_ESTIMATED { get; set; }
        public Nullable<decimal> HOURS_ACTUAL { get; set; }
        public Nullable<decimal> DOLLARS_ESTIMATED { get; set; }
        public Nullable<decimal> DOLLARS_ACTUAL { get; set; }
        public string OVERDUE { get; set; }
        public string TEAR_DOWN { get; set; }
        public Nullable<decimal> MIN_SCHED_BLOCK { get; set; }
        public string DATE_START { get; set; }
        public Nullable<decimal> TIME_START { get; set; }
        public string DATE_DUE { get; set; }
        public Nullable<decimal> MACHINE_HRS { get; set; }
        public string ALLOW_CHRG { get; set; }
        public string NO_ROUTER_UPDATE { get; set; }
        public string LOCN { get; set; }
        public string DATE_ARRIVED { get; set; }
        public Nullable<decimal> TIME_ARRIVED { get; set; }
        public string DATE_MATERIAL_DUE { get; set; }
        public string DATE_COMPLETED { get; set; }
        public Nullable<decimal> TIME_ELAPSED { get; set; }
        public Nullable<decimal> FACTOR_WORKCENTER { get; set; }
        public Nullable<decimal> FACTOR_FINITE { get; set; }
        public string DATE_HARD { get; set; }
        public Nullable<decimal> OVERLAP { get; set; }
        public string PART_PO { get; set; }
        public string SEQ_REV { get; set; }
        public string PROJ_GROUP { get; set; }
        public string DATE_PO_ORDER { get; set; }
        public string SEQ_PO { get; set; }
        public string PO_ASSIGNED { get; set; }
        public Nullable<decimal> YIELD { get; set; }
        public Nullable<decimal> YIELD_RATIO { get; set; }
        public string TASK_SEQ { get; set; }
        public string TASK_SIGNOFF_USER { get; set; }
        public string TASK_SIGNOFF_TYPE { get; set; }
        public string TASK_SIGNOFF_BY { get; set; }
        public string TASK_SIGNOFF_DATE { get; set; }
        public string CODE_SORT_OPER { get; set; }
        public Nullable<decimal> DATE_OPER_SK_YEAR { get; set; }
        public string DATE_OPER_SK_MDY { get; set; }
        public Nullable<decimal> DATE_OPER_ST_YEAR { get; set; }
        public string DATE_OPER_ST_MDY { get; set; }
        public Nullable<decimal> CREW_SIZE { get; set; }
        public Nullable<decimal> RATE_PIECE { get; set; }
        public Nullable<decimal> TIME_DUE { get; set; }
        public Nullable<decimal> FREQUENCY { get; set; }
        public Nullable<decimal> UNIT_D6 { get; set; }
        public string PREVIOUS_CLOSED { get; set; }
        public Nullable<decimal> PRICE_PERCENT { get; set; }
        public string MAIN_COMMENT { get; set; }
        public Nullable<decimal> LEAD_TIME { get; set; }
        public string MINIMUM_FLAG { get; set; }
        public Nullable<decimal> E_MINIMUM { get; set; }
        public string WORK_STARTED { get; set; }
        public string TOOLING_SEQ { get; set; }
        public string ORIG_RTR_SEQ { get; set; }
        public string HOLD_PO { get; set; }
        public string TASK_COMP_REQ { get; set; }
        public string TASK_MSG_NEEDED { get; set; }
        public string OTH_LANGUAGE { get; set; }
        public int ID { get; set; }
    }
}
