//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardTask
    {
        public long RecordNumber { get; set; }
        public Nullable<long> OnBoardPart { get; set; }
        public Nullable<long> Task { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> TaskSequence { get; set; }
        public Nullable<long> ChildOfTask { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Complexity { get; set; }
        public Nullable<decimal> StandardCompletionHours { get; set; }
        public Nullable<decimal> ActualCompletionHours { get; set; }
        public string Notes { get; set; }
        public string ResponsibleUser { get; set; }
        public string DelegatedTo { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<System.DateTime> DueBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string CompletedBy { get; set; }
        public string CurrentStatus { get; set; }
        public string CompletionStatus { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
    }
}
