//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnBoardingPartsToAdd
    {
        public long RecordNumber { get; set; }
        public string Company { get; set; }
        public string PartNumber { get; set; }
        public Nullable<System.DateTime> DateRequestedToAdd { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
    }
}
