//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnBoardingEntities1 : DbContext
    {
        public OnBoardingEntities1()
            : base("name=OnBoardingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<OnBoardingPartsToAdd> OnBoardingPartsToAdds { get; set; }
        public virtual DbSet<OnBoardPart> OnBoardParts { get; set; }
        public virtual DbSet<OnBoardTask> OnBoardTasks { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<PartMaster> PartMasters { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<Z_OnBoardPartJobs> Z_OnBoardPartJobs { get; set; }
        public virtual DbSet<Z_OnBoardPartOSSPO> Z_OnBoardPartOSSPO { get; set; }
        public virtual DbSet<AuthorizedOnBoardPart> AuthorizedOnBoardParts { get; set; }
        public virtual DbSet<AvailPlanJob> AvailPlanJobs { get; set; }
    }
}
