//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnTimeDelivery
    {
        public Nullable<int> NumOnTime { get; set; }
        public int NumTotal { get; set; }
        public int PercOnTime { get; set; }
        public string Period { get; set; }
    }
}
