//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTStage
    {
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> RateEmployee { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public string EmpID { get; set; }
    }
}
