//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public long RecordNumber { get; set; }
        public string ProgramID { get; set; }
        public string ParameterID { get; set; }
        public int ParameterSequence { get; set; }
        public decimal ParamN1 { get; set; }
        public decimal ParamN2 { get; set; }
        public string ParamS1 { get; set; }
        public string ParamS2 { get; set; }
        public string ParamS3 { get; set; }
        public string ParamS4 { get; set; }
    }
}
