//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastDueDeliverablesByReviewer
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public int UserID { get; set; }
        public string ReviewerName { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> DaysPast { get; set; }
    }
}
