//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMMCONNECTEntities : DbContext
    {
        public PMMCONNECTEntities()
            : base("name=PMMCONNECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CURRENT_MACHINE_INFORMATION> CURRENT_MACHINE_INFORMATION { get; set; }
        public virtual DbSet<JP_TimeInStateByMachine> JP_TimeInStateByMachine { get; set; }
        public virtual DbSet<JP_CurrentMachineState> JP_CurrentMachineState { get; set; }
    }
}
