//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevMaint
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public string MachineID { get; set; }
        public string Description { get; set; }
        public string MonthlyLastPmDate { get; set; }
        public string MonthlyNextPmDue { get; set; }
        public string QuarterlyLastPmDate { get; set; }
        public string QuarterlyNextPmDue { get; set; }
        public string AnnualLastPmDate { get; set; }
        public string AnnualNextPmDue { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> SumDowntime { get; set; }
        public int PlantID { get; set; }
    }
}
