//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingPlanAdjShipDate
    {
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> AdjShipDate { get; set; }
        public string OrderLine { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
    }
}
