//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingDetailAuditStatu
    {
        public string Job { get; set; }
        public string Suffix { get; set; }
        public string Seq { get; set; }
        public string PARTNUM { get; set; }
        public string DESCRIPTION { get; set; }
        public string WC { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_CLOSED { get; set; }
        public int ID { get; set; }
        public Nullable<int> Missing { get; set; }
        public Nullable<int> Hold { get; set; }
        public Nullable<int> Complete { get; set; }
        public Nullable<int> Total { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    }
}
