//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFAuditHIstoryTopLevel
    {
        public long ID { get; set; }
        public Nullable<int> AuditID { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string PlantName { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<decimal> Score { get; set; }
    }
}
