//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFCriteria
    {
        public int ID { get; set; }
        public Nullable<int> ChallengeID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
    }
}
