//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFPlantRollupByMonthHalf
    {
        public long ID { get; set; }
        public int PlantID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> PlantsScored { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public int Half { get; set; }
        public Nullable<decimal> Goal { get; set; }
    }
}
