//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_OnBoardPartJobs
    {
        public long RecordNumber { get; set; }
        public Nullable<long> PartRecordNumber { get; set; }
        public string PlanningJobNumber { get; set; }
        public string ProductionJobNumber { get; set; }
        public string SalesOrderNumber { get; set; }
        public string SalesOrderLine { get; set; }
    }
}
