//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_OnBoardPartOSSPO
    {
        public long RecordNumber { get; set; }
        public Nullable<long> PartRecordNumber { get; set; }
        public string JobOSSSequence { get; set; }
        public Nullable<System.DateTime> SchedStartDate { get; set; }
        public Nullable<System.DateTime> SchedEndDate { get; set; }
        public string OSSPONumber { get; set; }
        public string OSSPOLine { get; set; }
        public Nullable<System.DateTime> OSSPOLineDueDate { get; set; }
        public Nullable<System.DateTime> OSSPOStartDate { get; set; }
        public Nullable<System.DateTime> OSSPOReceiveDate { get; set; }
    }
}
