//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipDownloadLog
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Downloader { get; set; }
        public Nullable<System.DateTime> DateDownloaded { get; set; }
    }
}
