//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipFile
    {
        public int ID { get; set; }
        public string ZipName { get; set; }
        public string Location { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public Nullable<int> Uploader { get; set; }
    }
}
