//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BT_SPTransactions
    {
        public int RecordNumber { get; set; }
        public string JobCode { get; set; }
        public string TransactionTimeStamp { get; set; }
        public string TransType { get; set; }
        public string ProductName { get; set; }
        public string PartNo { get; set; }
        public string TransactionUser { get; set; }
        public string TransactionUserID { get; set; }
        public Nullable<double> ExpStartQty { get; set; }
        public Nullable<double> ActStartQty { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuantityPieces { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ProductDescription { get; set; }
        public string ProcessedOn { get; set; }
        public string PONumber { get; set; }
        public string POLine { get; set; }
        public string ReceiptRecordNumber { get; set; }
        public string FileName { get; set; }
        public string TransactionNumber { get; set; }
    }
}
