//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTStageThree
    {
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public string Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Week { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<decimal> RateEmployee { get; set; }
        public Nullable<decimal> OTHours { get; set; }
        public Nullable<decimal> OTRate { get; set; }
        public Nullable<decimal> OTCost { get; set; }
        public string EmpID { get; set; }
    }
}
