//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevMaintTemp
    {
        public string STATUS { get; set; }
        public string ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string MONTHLY_LAST_PM_DATE { get; set; }
        public string MONTHLY_NEXT_PM_DUE { get; set; }
        public string QUARTERLY_LAST_PM_DATE { get; set; }
        public string QUARTERLY_NEXT_PM_DUE { get; set; }
        public string ANNUAL_LAST_PM_DATE { get; set; }
        public string ANNUAL_NEXT_PM_DUE { get; set; }
        public Nullable<decimal> TOTAL_COST { get; set; }
        public Nullable<decimal> SUM_DOWNTIME { get; set; }
        public int PlantID { get; set; }
    }
}
