//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevMaintCost
    {
        public string ResourceID { get; set; }
        public string WorkOrderBaseID { get; set; }
        public Nullable<decimal> SumDowntime { get; set; }
        public string Type { get; set; }
        public int PlantID { get; set; }
    }
}
