//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapStageTemp
    {
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public string CN { get; set; }
        public Nullable<decimal> DISPOSED_VALUE { get; set; }
        public string DD { get; set; }
        public string PART { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string ACTION { get; set; }
        public string NAME { get; set; }
        public string JOB { get; set; }
        public string SUF { get; set; }
        public string SCODE { get; set; }
    }
}
