//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapStage
    {
        public string CompanyCode { get; set; }
        public string PlantCode { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<decimal> DisposedValue { get; set; }
        public string DateDisposed { get; set; }
        public string PartNum { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> QtyDisposed { get; set; }
        public string DispositionAction { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public string Suffix { get; set; }
        public string ScrapCode { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Day { get; set; }
        public int ID { get; set; }
    }
}
