//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrapMonthlyByCompany
    {
        public string CompanyCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public int ID { get; set; }
    }
}
