//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingPlanStage
    {
        public string OrderNo { get; set; }
        public string OrderLine { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<decimal> QtySched { get; set; }
        public string Customer { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public string Part { get; set; }
        public string Description { get; set; }
        public int ID { get; set; }
    }
}
