//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeInStateByMachine
    {
        public long ID { get; set; }
        public string Mode { get; set; }
        public string Status { get; set; }
        public string Machine { get; set; }
        public string CurrentMode { get; set; }
        public Nullable<decimal> TotalTimeInMode { get; set; }
    }
}
