//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFAuditDetail
    {
        public int ID { get; set; }
        public Nullable<int> AuditID { get; set; }
        public Nullable<int> CriteriaID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<bool> Selected { get; set; }
    }
}
