//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFAveragesByMonth
    {
        public long ID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public string PlantName { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<decimal> Average { get; set; }
    }
}
