//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orizon.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCFAuditDetailLevel
    {
        public long ID { get; set; }
        public Nullable<int> AuditID { get; set; }
        public string Auditor { get; set; }
        public string PlantName { get; set; }
        public string AreaName { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<int> CriteriaID { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> ChallengeID { get; set; }
        public string Challenge { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Category { get; set; }
    }
}
